### ISSUE TITLE
Can't npm it 

### ISSUE THREAD

**Issue by GoPixel-lab** [solana-labs/oyster-swap#8]
![image](https://user-images.githubusercontent.com/90441300/139899931-acf48706-5efc-41d9-975a-ad1f42257661.png)

**Comment by GoPixel-lab** [comment]
I tried yarn, it can success run until the last build falied as well

**Comment by RajaFaizanNazir** [comment]
Here is the list of commands I wrote for my help:
But make sure you upgrade the   "@solana/web3.js": "^0.78.2" to "@solana/web3.js": "^1.50.1" in package.json, because it will update the cluster URL of RPC of networks including 'devnet' and 'testnet'
`git clone https://github.com/solana-labs/oyster-swap`
`cd oyster-swap`
`set SWAP_PROGRAM_OWNER_FEE_ADDRESS='Your Wallet`
`set SWAP_HOST_FEE_ADDRESS='Your Wallet`
`npx browserslist@latest --update-db`
`sudo npm install -g serve`
`npm install --force @craco/craco --save`
`npm run build`
`serve -s build`

**Comment by graceful-coder** [comment]
After following the above instructions, I got dependency issues (this is an older project) that I resolved by running `npm install --legacy-peer-deps` and adding `SKIP_PREFLIGHT_CHECK=true` to the .env file. Then you should be able to successfully `npm run build` and `serve -s build` to see the UI.

**Comment by weck25** [comment]
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (F:\solana\oyster-swap\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (F:\solana\oyster-swap\node_modules\webpack\lib\NormalModule.js:417:16)
    at F:\solana\oyster-swap\node_modules\webpack\lib\NormalModule.js:452:10
    at F:\solana\oyster-swap\node_modules\webpack\lib\NormalModule.js:323:13
    at F:\solana\oyster-swap\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at F:\solana\oyster-swap\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (F:\solana\oyster-swap\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at F:\solana\oyster-swap\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.9.0

i have error openssl when i run npm run build
